[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/pdfjs-dist/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    # Increases the default serverless function timeout to 30s
    # (requires at least a Netlify Pro plan for values > 10s)
    serverFunctionTimeout = 30000
